### PR TITLE
Gsm Server Example

### PR DESCRIPTION
**Pull request by FrancMunoz**
MKR GSM Server that executes a remote command to open or close a led. Uses buffered reading data from SARA-U201 and it's able to attend HTTP and socket TPC/IP requests.

### CODE REVIEW

**Comment by FrancMunoz** [comment]
Hi @sandeepmistry !

Yes, I like the approach of #44, it's cleaner and less coding needed. So, will wait until #44 is approved and then close this PR.

Thank you!

**Comment by FrancMunoz** [comment]
Hi @sandeepmistry , 

I will have to open another PR for GSM Server example, If you agree, to avoid working for nothing, I would like to update example with #44, cleaning buffering in code and the make another PR (I deleted the original repository by error), what do you think?

Also, what do you think @sandeepmistry  and @facchinm, about provide examples joining technologies... I mean, I'm able to provide examples using MKRGSM and, Ionic, cordova or xamarin in mobile, node.js for socket server and so on, that would bring an out-of-the-box experience joining mobile/server and MKR... and also the users just to feed new ideas... what do you think?

Thank you!

**Comment by sandeepmistry** [comment]
> Also, what do you think @sandeepmistry and @facchinm, about provide examples joining technologies... I mean, I'm able to provide examples using MKRGSM and, Ionic, cordova or xamarin in mobile, node.js for socket server and so on, that would bring an out-of-the-box experience joining mobile/server and MKR... and also the users just to feed new ideas... what do you think?

This is something a bit more complex for a built in example in my opinion. However, Arduino Project hub would be a good place for things like this: https://create.arduino.cc/projecthub

**Comment by FrancMunoz** [comment]
Oh! sure! thank you for the information, didn't notice about project hub.

**Comment by sandeepmistry** [comment]
As discussed above, closing this in favour of https://github.com/arduino-libraries/MKRGSM/pull/44

**Pull request closed without merging**
