### PR TITLE
[DO NOT MERGE] Add timeout on GSM, GPRS, GSMServer, GSMClient and GSM_SMS

### PR DESCRIPTION
**Pull request by Rocketct**
Added time in accord with At command manual, in ready function of GMS, GPRS, GSMCLient,GSM_SMS and GSMServer .cpp files,
these changes allow to avoid loop due to ready() check loop and force the software to return in the main sketch, the time out value are alligned with the ones
of the At command manual, where not specified was actually forced a timeout of 7 minutes.

### CODE REVIEW

**Comment by sandeepmistry** [comment]
@Rocketct is it easy to reproduce the cases where AT command responses are timing out?

**Comment by Rocketct** [comment]
I force it by plug and unplug the antenna while are in connection phase, but is not so simple make that happen, instead after a while (in long run test) it occurs but if unlucky you have to wait a lot of time. However what is happen is that for some reason the samd loose the echo command by the SARA and for this reason the UART is never available here:

 https://github.com/arduino-libraries/MKRGSM/blob/master/src/Modem.cpp#L228 

And the code loop in point like this in GSMClient.cpp: 

https://github.com/arduino-libraries/MKRGSM/blob/master/src/GSMClient.cpp#L215  

simply following the chain of ready function called start from GSMClient.cpp#L215  you will see that it never goes out from the loop because before of the state machine in each ready (GSM, GPRS ...) before is checked the ready() and after there is the state machines switch:

https://github.com/arduino-libraries/MKRGSM/blob/master/src/GSMClient.cpp#L63

However in general it could happen in each point where we have a while that loop on ready()without escape condition and for some reason the uart doesn't make a response.

**Comment by Rocketct** [comment]
i have tested it with the following sketch:
 ```c++
/*
  Simple PUT client for ArduinoHttpClient library
  Connects to server once every five seconds, sends a PUT request
  and a request body

  created 14 Feb 2016
  by Tom Igoe

  update by M. Sibert May 2018

  this example is in the public domain
*/

#include <MKRGSM.h>
#include <ArduinoHttpClient.h>
#include "arduino_secrets.h"



const String serverName(("httpbin.org"));
const unsigned serverPort = 80;
const String servicePath(("/put"));

const String GPRS_APN((APN_NAME));
const String GPRS_LOGIN((APN_USERNAME));
const String GPRS_PASSWORD((APN_PASSWORD));

unsigned long initTime = millis();

GSM gsm(true);
GPRS gprs;
GSMClient gprsClient;

HttpClient client = HttpClient(gprsClient, serverName, serverPort);

const String contentType = "application/json";
const String putData = "{ \"name\": \"light\", \"age\": 46 }";
unsigned long int count = 0;
boolean connected;

void setup() {
  Serial.begin(115200);

  MODEM.begin();
  connected = false;
  while (!connected) {
    if ((gsm.begin(PIN_CODE) == GSM_READY) &&
        (gprs.attachGPRS(GPRS_APN.c_str(), GPRS_LOGIN.c_str(), GPRS_PASSWORD.c_str()) == GPRS_READY)) {
      connected = true;
    } else {
      Serial.println("Not connected");
      delay(1000);
    }
  }
  Serial.println("Connected");
}

void loop() {

  /* Here is checked if the connection is lost, simply check the CREG status
     there you can also count the tentative number until when you could stop to reconect and do other
     you could do somthing like this also in the setup() imposing some condition in the line:45 in the "while (!connected)"
  */
  if (gsm.isAccessAlive()) {

    Serial.println("PUT request");
    int ret = client.put(servicePath.c_str(), contentType, putData);
    if (ret < 0) {
      Serial.println("Bad request");
      Serial.println(ret);
      client.flush();
      client.stop();
    } else {
      Serial.println(" PUT request done");

      unsigned long looptime = millis();

      while (client.available() <= 0 && millis() - looptime < 5000) {
      }
      if (client.available()) {
        // read the status code and body of the response
        const int statusCode = client.responseStatusCode();
        const String response = client.responseBody();
        if (statusCode != 200) {
          client.flush();
          client.stop();
        } else {
          Serial.print("Status code: ");
          Serial.println(statusCode);
          Serial.print("Response: ");
          Serial.println(response);
          Serial.print(count);
          count++;
          Serial.print("Connections: ");
          Serial.println(count);
        }
      }
    }
    //unsigned long start = millis();

    if (!client.connected()) {
      connected = false;
      client.flush();
      client.stop();
      
      gsm.shutdown();
    }
    delay(1000);
    while (!connected) {
      
      if ((gsm.begin(PIN_CODE) == GSM_READY) &&
          (gprs.attachGPRS(GPRS_APN.c_str(), GPRS_LOGIN.c_str(), GPRS_PASSWORD.c_str()) == GPRS_READY)) {
        connected = true;
      } else {
        Serial.println("Not connected");
        delay(1000);
      }
    }

  } else {
    Serial.println("not connected, loop:sketch ");
    delay(1000);
  }

}
```

**Comment by Rocketct** [comment]
ok @sandeepmistry  let me know if i can test today or next week

**Comment by sandeepmistry** [comment]
@Rocketct please see: https://github.com/arduino-libraries/MKRGSM/pull/52

**Comment by Rocketct** [comment]
ok @sandeepmistry  i'll check immediately

**Pull request closed without merging**
