### PR TITLE
Added GSMClient:downloadString() function

### PR DESCRIPTION
**Pull request by FrancMunoz**
This function allow to download string using HTTP allowing using SSL using buffered read from SARA and also limiting the return if desired.

### CODE REVIEW

**Comment by FrancMunoz** [comment]
Use:

`String GSMClient::downloadString(const char server[], const char path[], bool ssl, int port, int limit);`

**server** - Name of the server to download string: www.zeroworks.com
**path** - Route to resource ex: /index.htm
**ssl** * - Use SSL.
**port** * - port to connect, defaults to 80 in http and 443 in https.
**limit** * - max lenght of returned string, the remaining downloaded data will be discarded.

_* Not required._

Example to download asciilogo from arduino.cc using ssl:

```
GSMClient client;
Serial.println(client.downloadString("arduino.cc", "/asciilogo.txt", true));
```

**Comment by sandeepmistry** [comment]
Hi @FrancMunoz,

Thank you for taking the time to open this pull request.

However, at this time I think it's best to have `GSMClient` stick to Arduino's original `Client` API and not introduce new methods. Especially, something higher level related to HTTP.

**Comment by FrancMunoz** [comment]
And what about an http class whit this kind of wrappers?

**Comment by sandeepmistry** [comment]
We have the following library: https://github.com/arduino-libraries/ArduinoHttpClient

**Comment by FrancMunoz** [comment]
Lol, i'm feeling from another world... didn't noticed about that too... my google should not work well ... I apologize to bother you. Thank you again!

**Pull request closed without merging**
