### PR TITLE
Add new GSMSecurity API for TLS/SSL certificates

### PR DESCRIPTION
**Pull request by daz**
This API handles importing SSL/TLS certificates to the modem and using them on a connection.

Some things:

- The example connects to AWS IoT, it could be swapped for something simpler (with legit certs so people can test it)
- Is `const char SECRET_ROOT_CERT[] PROGMEM = "MIIE0zC..."` the best way to store the certs? Or maybe a byte array?
- I'm not sure if my naming is perfect, `GSMSecurity`
- Does it need to implement `begin()`?
- Currently doesn't support multiple profiles, but easily can 
- Need to implement listing and removing installed certs, because they persist on the modem between boots, the modem maxes out at 9 certs, and it will throw an error while importing if you exceed

My C++ knowledge is very limited and SSL/TLS knowledge is literally zero lol so please be thorough...

### CODE REVIEW

**Comment by ArnoSoontjens** [comment]
Hi guys,
Having this would be great, will this be merged?

**Comment by daz** [comment]
It would have to be modified to work with b615cb34ce528208ace9f325c6f50a3973627551

**Comment by conradbielski** [comment]
Hi Daz, I'm testing your mqtt code with AWS IoT and I'm not able to connect. I know it's not at the AWS side since I've been able to publish with another client (non Arduino) with the same certs.

From the PubSubClient, I'm getting an MQTT_CONNECT_FAILED -2. I'm trying to figure out where else to look to get the example GsmSecurity running.
Thanks for your help,
Conrad

**Comment by daz** [comment]
Have you turned on `MODEM.debug()` and seen what fails?

**Comment by conradbielski** [comment]
Thanks for that suggestion (didn't realise I can do it).
So, now I see and error from the modem but have no idea how to interpret. After calling mqttClient.connect(clientId), the following debug info gets printed:
Connecting...
AT+USOCR=6
+USOCR: 0
OK
AT+USOSEC=0,1,0
OK
AT+USOCO=0,"azux5q4yqlajd-ats.iot.eu-west-1.amazonaws.com",8883
ERROR
AT+USOCL=0
ERROR

Then it retries...
Any ideas? Since it occurs when connecting with the endpoint, I'm wondering if it's a certificate issue (formatting/size?). Is there a way to figure out whether the Certificates were accepted?
Thanks in advance

**Comment by conradbielski** [comment]
Thanks Daz for pointing me to a deeper dive into the issue. I found the problem but not sure how to solve it. Hope you have some ideas.
So, as my previous post showed, the AT commands return 'OK' when reading the certificates. However, if you add the MODEM.sendf("AT+CMEE=2"); command, you get even more details...

When importing the certificates, the following error shows up:
+CME ERROR: text string too long
for all three certificates. Now, in your code (ino file), the secret file is a "const char SECRET_ROOT_CERT[] PROGMEM" whereas in the GSMSecurity file it is a "const char*". Is this the problem? And if so, how to fix it?

This is the command (I believe) that is complaining:
MODEM.sendf("AT+USECMNG=0,%d,\"%s\",%d", type, name, strlen(cert) + 2);
about the text string being too long. Any ideas how to fix the issue?

Thanks again for your help.

**Comment by conradbielski** [comment]
Hi Daz,
after searching and testing I think I finally figured out what the problem is. The u-blox GSM on the Arduino MKR GSM 1400 model (u-blox model SARA-U201) does not support the secure option.
(see https://www.u-blox.com/sites/default/files/AT-CommandsExamples_AppNote_%28UBX-13001820%29.pdf - page 104).
Can you confirm this?
I hope that it might help others trying to connect to AWS IoT which requires the certificates but the u-blox model can't handle.
Have a great day

**Comment by TechNyquist** [comment]
Any chance to have this merged? Importing custom certificates it's a "must to have" feature in a more and more secure IoT world, IMO. Much hype to this.

**Comment by jandusek** [comment]
+1 to have this merged, very essential feature in my humble opinion

**Comment by devfubar** [comment]
> Hi Daz,
> after searching and testing I think I finally figured out what the problem is. The u-blox GSM on the Arduino MKR GSM 1400 model (u-blox model SARA-U201) does not support the secure option.
> (see https://www.u-blox.com/sites/default/files/AT-CommandsExamples_AppNote_%28UBX-13001820%29.pdf - page 104).
> Can you confirm this?
> I hope that it might help others trying to connect to AWS IoT which requires the certificates but the u-blox model can't handle.
> Have a great day

I believe this is the case.

Has anyone else used this code to get an Arduino talking to AWS IoT. If so what did you model did you use?

**Comment by daz** [comment]
This code worked, but hasn't since b615cb34ce528208ace9f325c6f50a3973627551 where root certs and their insertion method were added. My MKR GSM 1400 has been happily uploading to AWS since last year, but it's using my branch of this library and hasn't been updated since.

My code is crappy that's all. @sandeepmistry's work on adding root certs is way better but currently only allows for root certs. I don't think it'd be too hard to add the ability to load user client certs and private keys

**Comment by TechNyquist** [comment]
@daz I think you may tell your code as crappy as you want, but it works. It's the only way I found so far to connect to AWS IoTCore.
AWS IoTCore requires peer authentication, so client certificate and private key are mandatory; your GSMSecurity files copied on MKRGSM (and "#include "GSMSecurity.h" in MKRGSM.h) is the only way to achieve this by now, as it exposes methods for that. I really don't get the reason for which this is taking so long to be accepted (it needs improvements, ok, but better than nothing).

By the way, the above code works ok as long as you don't "attachGPRS" again (for session expire ie), then TLS facility won't work anymore and connection fail. I'm trying to understand how to workaround this without the need to clear certificates and set them again on the uBlox (that is the only way to make it work again so far).

**Comment by TechNyquist** [comment]
Ok I got it to work again merged with updated MKRGSM.
I'd lend you the changes, but I don't know how to update the code of this PR or your fork (GitHub won't allow me to fork your repo).

**Comment by CCorrado** [comment]
+bump, this would be awesome to have for the MKR GSM 1400 for folks connecting them to AWS IoT. Looks like there's a few conflicts, any reason they cannot be resolved? Experimenting with this branch now :)

**Comment by daz** [comment]
Looks like 238469d01549c673fbe9e1f01b085db4d42888e4 closes this 🎉

**Pull request closed without merging**
